// App-owned UI strings. External app, file, window, and native menu names are never translated.
import Foundation

extension L10n {
    static let korean: [String: String] = [
        "Use macOS Dock When No External Display Is Connected": "외부 모니터가 없으면 기본 Dock 사용",
        "Pauses everyDock and its background monitoring on the built-in display alone. Reconnect an external display to resume automatically.": "내장 화면만 사용할 때 everyDock과 백그라운드 감시를 멈춥니다. 외부 모니터를 다시 연결하면 자동으로 재개합니다.",
        "Paused — using macOS Dock until an external display is connected.": "일시 중지됨 — 외부 모니터를 연결할 때까지 기본 Dock을 사용합니다.",
        "The app order was saved in everyDock, but could not be synced to macOS Dock. Try moving the app again.": "everyDock에 앱 순서는 저장했지만 기본 Dock에 반영하지 못했습니다. 앱을 다시 이동해 주세요.",
        "Press and hold an app or separator for 0.30 seconds, then drag to reorder. Move an app into the pinned section to pin it, or into the running section to unpin it. App order and pins sync both ways with macOS Dock. everyDock keeps its own separators.": "앱이나 구분선을 0.30초간 누른 뒤 끌어서 순서를 바꾸세요. 앱을 고정 영역으로 옮기면 고정되고, 실행 영역으로 옮기면 고정이 해제됩니다. 앱 순서와 고정 상태는 기본 Dock과 양방향으로 동기화됩니다. everyDock의 구분선은 그대로 유지됩니다.",
        " — Launching…": " — 실행 중…",
        "‹ Back": "‹ 이전 메뉴",
        "{0} displays": "디스플레이 {0}개",
        "{0} is empty.": "{0} 폴더가 비어 있습니다.",
        "{0} windows": "창 {0}개",
        "%.2f s": "%.2f초",
        "1 display": "디스플레이 1개",
        "1 window": "창 1개",
        "Active": "활성 앱",
        "Add": "추가",
        "Add Apps…": "앱 추가…",
        "Add Separator": "구분선 추가",
        "Add Separator After": "이 앱 뒤에 구분선 추가",
        "Add Separator Before": "이 앱 앞에 구분선 추가",
        "Add Separator Here": "여기에 구분선 추가",
        "Allow": "허용",
        "Allow Accessibility access in System Settings to select, minimize, and restore app windows.": "앱 창을 선택하고 최소화·복원하려면 손쉬운 사용 권한이 필요합니다. 시스템 설정에서 everyDock을 허용해 주세요.",
        "Allow Accessibility access to see open windows.": "창 목록을 읽으려면 손쉬운 사용 접근을 허용해 주세요.",
        "Allow Accessibility…": "손쉬운 사용 허용…",
        "Screen Recording Settings…": "화면 녹화 설정 열기…",
        "Allow Folder Access…": "폴더 접근 허용…",
        "Allow Screen Recording": "화면 녹화 허용",
        "Allow Screen Recording…": "화면 녹화 허용…",
        "Allowed": "사용 가능",
        "App menu access was denied. Check Accessibility permission.": "앱 메뉴 접근이 거부되었습니다. 손쉬운 사용 권한을 확인해 주세요.",
        "App menu error: {0}. You can use the everyDock commands below.": "앱 메뉴 오류: {0}. 아래의 everyDock 메뉴를 사용할 수 있습니다.",
        "Appearance": "Dock 모양",
        "Approve Login Item in System Settings…": "시스템 설정에서 로그인 항목 승인…",
        "Bottom": "아래",
        "Cancel": "취소",
        "Cannot access {0}. Allow access to this folder.": "{0} 폴더에 접근할 수 없습니다. 폴더 접근을 허용해 주세요.",
        "Cannot find {0}. Unpin it and add the app again.": "{0}을(를) 찾을 수 없습니다. 고정을 해제한 뒤 앱을 다시 추가해 주세요.",
        "Check Permission Status": "권한 다시 확인",
        "Checking…": "확인 중…",
        "Choose Allow Screen Recording to see previews. You can still select or close windows by title.": "창 이미지를 보려면 ‘화면 녹화 허용’을 눌러 주세요. 제목으로 창을 선택하거나 닫을 수 있습니다.",
        "Choose Apps to Pin": "Dock에 고정할 앱 선택",
        "Choose Get Started to apply this option. You can change it later in Settings.": "‘시작하기’를 누르면 이 선택을 적용합니다. 나중에 설정에서 바꿀 수 있습니다.",
        "Click Active App to Minimize": "활성 앱을 다시 클릭하면 최소화",
        "Close": "닫기",
        "Close {0}": "{0} 창 닫기",
        "Close All Windows": "모든 창 닫기",
        "Close this window": "이 창 닫기",
        "Copy": "복사",
        "Could not close the window. macOS error: {0}": "창을 닫지 못했습니다. macOS 오류: {0}",
        "Could not find the macOS Apps launcher. Open Spotlight and press ⌘1 to browse apps.": "macOS의 Apps 실행기를 찾지 못했습니다. Spotlight에서 ⌘1을 눌러 앱을 열어 주세요.",
        "Could not load window previews: {0}": "창 이미지를 가져오지 못했습니다: {0}",
        "Could not manage the macOS Dock: {0}": "기본 Dock을 관리하지 못했습니다: {0}",
        "Could not open Apps: {0}": "Apps를 열지 못했습니다: {0}",
        "Could not open the app: {0}": "앱을 열 수 없습니다: {0}",
        "Could not open this item. Check its location in Finder.": "항목을 열지 못했습니다. Finder에서 위치를 확인해 주세요.",
        "Could not read {0}: {1}": "{0} 폴더를 읽지 못했습니다: {1}",
        "Could not read pinned apps from the macOS Dock. Choose Add Apps to select them manually.": "기본 Dock의 고정 앱을 읽지 못했습니다. ‘앱 추가’로 직접 선택할 수 있습니다.",
        "Could not read the app’s windows. Try again in a moment.": "앱의 창 목록을 읽지 못했습니다. 잠시 후 다시 시도해 주세요.",
        "Could not update the login item: {0}": "로그인 항목을 변경하지 못했습니다: {0}",
        "Cut": "잘라내기",
        "Denied by macOS": "macOS에서 거부됨",
        "Desktop": "바탕화면",
        "Detect Displays Again": "디스플레이 다시 감지",
        "Development": "개발",
        "Displays": "표시할 디스플레이",
        "Distance from Screen Edge": "화면 가장자리 간격",
        "Downloads": "다운로드",
        "Edit": "편집",
        "Effective Size": "현재 적용 크기",
        "Empty the Trash?": "휴지통을 비우겠습니까?",
        "Empty Trash": "휴지통 비우기",
        "Empty Trash…": "휴지통 비우기…",
        "everyDock — A Dock on every display": "everyDock — 모든 화면의 Dock",
        "everyDock Menu": "everyDock 메뉴",
        "everyDock Menu · Scroll to see more apps": "everyDock 메뉴 · 스크롤로 나머지 앱 표시",
        "everyDock Settings": "everyDock 설정",
        "everyDock Settings…": "everyDock 설정…",
        "Finish saving or closing the window in the app. The remaining windows were left open.": "앱에서 저장 확인이나 창 닫기를 완료해 주세요. 나머지 창은 닫지 않았습니다.",
        "Follow macOS Dock Size and Magnification": "기본 Dock의 크기·확대 설정 따르기",
        "Follow System": "시스템 설정 따르기",
        "General": "일반",
        "Get Started": "시작하기",
        "Hidden": "숨겨짐",
        "Hide All Docks": "모든 Dock 일시 숨기기",
        "Hide macOS Dock While everyDock Is Running": "everyDock 사용 중 기본 Dock 숨기기",
        "Hide Menu Bar Icon": "메뉴 막대 아이콘 가리기",
        "Icon Size": "아이콘 크기",
        "If macOS denies access even with permission enabled, quit everyDock, remove its old entry in System Settings, and add the app shown by Show App Location. Then launch it again. Updating an ad-hoc signed build can invalidate an earlier approval.": "권한 스위치가 켜져 있는데 macOS가 접근을 거부하면 everyDock을 종료하고 시스템 설정에서 기존 항목을 제거한 뒤, ‘현재 앱 위치 보기’의 앱을 다시 등록하고 실행해 주세요. 임시 서명 빌드를 교체하면 기존 허용이 유지되지 않을 수 있습니다.",
        "Import from macOS Dock": "기본 Dock에서 가져오기",
        "Items in this user account’s Trash will be permanently deleted. Trash on external drives is not included. This cannot be undone.": "현재 사용자 계정의 휴지통에 있는 항목이 영구적으로 삭제됩니다. 외장 드라이브의 휴지통은 포함하지 않습니다. 이 작업은 취소할 수 없습니다.",
        "Language": "언어",
        "Launch everyDock at Login": "로그인 시 everyDock 실행",
        "Launching…": "실행 중…",
        "Left": "왼쪽",
        "macOS denied screen access for this app. If permission is already enabled, the registered app may have a different signature.": "macOS가 현재 실행 중인 앱의 화면 접근을 거부했습니다. 이미 켜져 있다면 앱 등록과 실행 파일의 서명이 달라졌을 수 있습니다.",
        "macOS denied screen access. You can still select or close windows by title.": "macOS가 현재 앱의 화면 접근을 거부했습니다. 제목으로 창을 선택하거나 닫을 수 있습니다.",
        "macOS denied window control for everyDock. If permission is enabled, the registered app may have a different signature. Use Check Permission Status and Show App Location in Settings.": "macOS가 현재 실행 중인 everyDock의 창 제어를 거부했습니다. 이미 허용했다면 등록된 앱과 현재 앱의 서명이 달라졌을 수 있습니다. 설정의 ‘권한 다시 확인’과 ‘현재 앱 위치 보기’를 이용해 주세요.",
        "macOS denied window control. Check Accessibility permission.": "macOS가 창 제어를 거부했습니다. 손쉬운 사용 권한을 확인해 주세요.",
        "Magnification": "포인터 확대",
        "Minimize": "최소화",
        "Minimize and Restore": "창 최소화·복원",
        "Minimized": "최소화됨",
        "Move Earlier": "앞으로 이동",
        "Move Later": "뒤로 이동",
        "New displays get a Dock automatically. If you disable every display, use the menu bar or reopen everyDock to enable them again.": "새 모니터를 연결하면 자동으로 Dock이 나타납니다. 화면을 모두 꺼도 메뉴 막대에서 다시 켤 수 있습니다.",
        "Newest modified first · Up to 80 items": "수정일 최신순 · 최대 80개",
        "No windows to show.": "표시할 창이 없습니다.",
        "Not Checked": "확인 전",
        "Not Running": "실행되지 않음",
        "OK": "확인",
        "Open": "열기",
        "Open {0}": "{0} 열기",
        "Open Accessibility Settings": "손쉬운 사용 설정 열기",
        "Open Desktop Folder": "바탕화면 폴더 열기",
        "Open Folder Access Settings…": "폴더 접근 설정 열기…",
        "Open in Finder": "Finder에서 열기",
        "Open Login Item Settings": "로그인 항목 승인 설정 열기",
        "Open Setup Guide…": "초기 설정 안내 다시 열기…",
        "Paste": "붙여넣기",
        "Pin to Dock": "Dock에 고정",
        "Pinned Apps": "고정 앱",
        "Position": "위치",
        "Preview Delay": "미리보기 대기 시간",
        "Preview Images": "미리보기 이미지",
        "Previews are shown for up to 8 windows. You can select and close every window.": "이미지는 최대 8개 창에 표시됩니다. 모든 창을 선택하고 닫을 수 있습니다.",
        "Previews stay in memory and are never saved or sent anywhere. Select a preview to switch to that window.": "미리보기는 메모리에서만 처리하며 파일로 저장하거나 전송하지 않습니다. 미리보기 창을 클릭하면 해당 창으로 전환합니다.",
        "Quit": "종료",
        "Quit everyDock": "everyDock 종료",
        "Quit everyDock before trying to uninstall it again.": "실행 중인 everyDock을 종료한 뒤 다시 제거해 주세요.",
        "Remove Separator": "구분선 삭제",
        "Reorder or remove pinned apps and separators here, or ⌘-drag them in the Dock. Drag a running app into the pinned section to pin it, or a pinned app into the running section to unpin it. Right-click an icon or a gap between pinned apps to add a separator.": "고정 앱과 구분선을 같은 목록에서 이동·삭제할 수 있습니다. Dock에서 ⌘ 키를 누른 채 드래그하면 순서가 바뀝니다. 실행 앱을 고정 영역으로 끌어오면 고정되고, 고정 앱을 실행 영역으로 옮기면 고정이 해제됩니다. 고정 앱 사이 또는 아이콘을 우클릭해 구분선을 추가하세요.",
        "Right": "오른쪽",
        "Running": "실행 중",
        "Saves your macOS Dock settings and enables auto-hide. Quitting, hiding all Docks, or a crash restores those settings. The macOS Dock restarts when this changes.": "원래 Dock 설정을 저장하고 자동 숨김을 적용합니다. everyDock 종료·일시 숨기기·비정상 종료 시 원래 설정을 복원합니다. 변경 시 기본 Dock이 한 번 재시작됩니다.",
        "Screen Recording permission enables window previews on hover. Images stay in memory; audio is never recorded.": "마우스를 올렸을 때 창 이미지를 보려면 화면 녹화 권한이 필요합니다. 이미지는 메모리에만 보관하며 오디오는 녹음하지 않습니다.",
        "Select All": "모두 선택",
        "Separator": "구분선",
        "Set Up Later": "나중에 설정",
        "Set up your Dock for every display.": "모든 화면의 Dock을 편하게 사용할 준비를 해요.",
        "Settings…": "설정…",
        "Show All Docks": "모든 Dock 다시 표시",
        "Show App Location": "현재 앱 위치 보기",
        "Show in Finder": "Finder에서 보기",
        "Show over Full-Screen Apps": "전체 화면 앱 위에도 표시",
        "Show Running Apps": "실행 중인 앱도 표시",
        "Show Window Previews on Hover": "마우스를 올리면 창 미리보기",
        "Show Windows…": "열린 창 보기…",
        "Some previews are unavailable. Select a title to open its window.": "일부 창 이미지를 가져오지 못했습니다. 제목을 눌러 창을 열 수 있습니다.",
        "System Settings…": "시스템 설정…",
        "The app did not respond to the window request in time. Try again in a moment.": "앱이 창 제어 요청에 제때 응답하지 않았습니다. 잠시 후 다시 시도해 주세요.",
        "The app has quit.": "앱이 종료되었습니다.",
        "The app is not responding. Try again in a moment.": "앱이 응답하지 않습니다. 잠시 후 다시 시도해 주세요.",
        "The app menu has changed. Open it again to choose a command.": "앱 메뉴가 변경되었습니다. 다시 열어 선택해 주세요.",
        "The app menu is not responding. Try again.": "앱 메뉴가 응답하지 않습니다. 다시 시도해 주세요.",
        "The login item is waiting for approval in System Settings.": "자동 실행 등록이 시스템 승인을 기다리고 있습니다.",
        "The window action failed. macOS error code: {0}": "창 조작에 실패했습니다. macOS 오류 코드: {0}",
        "This app’s Dock menu is unavailable. You can use the everyDock commands below.": "이 앱의 Dock 메뉴를 읽을 수 없습니다. 아래의 everyDock 메뉴를 사용할 수 있습니다.",
        "This window does not support closing": "이 창은 닫기를 지원하지 않습니다",
        "This window does not support closing.": "이 창은 닫기 기능을 제공하지 않습니다.",
        "This window does not support macOS minimization.": "이 창은 macOS 최소화 기능을 제공하지 않습니다.",
        "This window is already closed.": "이 창은 이미 닫혔습니다.",
        "To open Settings, find everyDock in Apps and launch it. Settings opens even if everyDock is already running.": "설정을 열려면 앱 메뉴(Apps)에서 everyDock을 찾아 실행하세요. 이미 실행 중이어도 설정 창이 열립니다.",
        "Trash": "휴지통",
        "Unpin": "고정 해제",
        "Unpin from Dock": "Dock에서 고정 해제",
        "Uses Korean when the system language is Korean; otherwise English.": "시스템 언어가 한국어이면 한국어로, 그 외에는 영어로 표시합니다.",
        "Uses the window’s yellow minimize button for the macOS animation. If access is missing, everyDock asks you to allow it. The animation follows the macOS Dock’s minimize effect setting.": "창의 노란 최소화 버튼을 통해 macOS 애니메이션을 실행합니다. 권한이 없을 때는 창을 숨기는 대신 권한을 안내합니다. 요술램프 효과는 시스템 Dock의 ‘윈도우 최소화 효과’ 설정을 따릅니다.",
        "Waiting for folder access. Check the macOS permission request for {0}.": "폴더 접근 응답을 기다리고 있습니다. macOS의 {0} 폴더 접근 요청을 확인해 주세요.",
        "Welcome to everyDock": "everyDock 시작하기",
        "Window": "윈도우",
        "Window Control": "창 제어",
        "Window control: {0}": "창 제어 결과: {0}",
        "Window Previews": "창 미리보기",
        "You can grant permissions later.": "권한은 나중에 허용해도 됩니다.",
        "Your Dock. On every display.": "모든 화면에, 언제나 나의 Dock.",
    ]
}
